# Generated by Django 4.1.7 on 2023-02-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verify',
            new_name='validate',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='verify_code',
            new_name='validate_code',
        ),
    ]
