# Generated by Django 4.1.7 on 2023-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=9)),
                ('sms_code', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
